### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by duffn** [ruby-grape/grape-on-rack#37]
- I tried this locally on Ruby 2.6.5

```
$ ruby -V
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
$ bundle install
$ rackup
$ curl http://localhost:9292/api/ping
[2022-06-14 19:23:08] INFO  WEBrick 1.4.2
[2022-06-14 19:23:08] INFO  ruby 2.6.5 (2019-10-01) [x86_64-darwin18]
[2022-06-14 19:23:08] INFO  WEBrick::HTTPServer#start: pid=75523 port=9292
NoMethodError: undefined method `[]' for nil:NilClass
```

- I tried this in GitHub Actions with the same result https://github.com/duffn/grape-on-rack/runs/6891598269?check_suite_focus=true

```
  1) Acme::API plain_text returns plain text
     Failure/Error: get '/api/plain_text'
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./vendor/bundle/ruby/2.6.0/gems/grape-1.2.4/lib/grape/router.rb:163:in `cascade?'
     # ./vendor/bundle/ruby/2.6.0/gems/grape-1.2.4/lib/grape/router.rb:95:in `transaction'
     # ./vendor/bundle/ruby/2.6.0/gems/grape-1.2.4/lib/grape/router.rb:72:in `identity'
     # ./vendor/bundle/ruby/2.6.0/gems/grape-1.2.4/lib/grape/router.rb:57:in `block in call'
     # ./vendor/bundle/ruby/2.6.0/gems/grape-1.2.4/lib/grape/router.rb:137:in `with_optimization'
     # ./vendor/bundle/ruby/2.6.0/gems/grape-1.2.4/lib/grape/router.rb:56:in `call'
     # ./vendor/bundle/ruby/2.6.0/gems/grape-1.2.4/lib/grape/api/instance.rb:154:in `call'
     # ./vendor/bundle/ruby/2.6.0/gems/grape-1.2.4/lib/grape/api/instance.rb:70:in `call!'
     # ./vendor/bundle/ruby/2.6.0/gems/grape-1.2.4/lib/grape/api/instance.rb:65:in `call'
     # ./vendor/bundle/ruby/2.6.0/gems/grape-1.2.4/lib/grape/api.rb:51:in `call'
     # ./vendor/bundle/ruby/2.6.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # ./vendor/bundle/ruby/2.6.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # ./vendor/bundle/ruby/2.6.0/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
     # ./vendor/bundle/ruby/2.6.0/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
     # ./spec/api/content_type_spec.rb:12:in `block (3 levels) in <top (required)>'
```

**Comment by dblock** [comment]
This is https://github.com/ruby-grape/grape/issues/1966. Let's get CI kicking here again and we can fix this by a `bundle update`. There are two other spec failures after this but they shouldn't be hard to fix. I started in https://github.com/ruby-grape/grape-on-rack/pull/38

**Comment by duffn** [comment]
`master` works now. Thanks.
